apiVersion: v2
name: gpu-operator
version: @OPERATOR_VERSION@
kubeVersion: ">= 1.13.0-0"
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
appVersion: "@OPERATOR_VERSION@"
home: https://github.com/NVIDIA/gpu-operator
