apiVersion: v2
name: gpu-operator
version: 1.0.1
kubeVersion: ">= 1.13.0-0"
description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
appVersion: 1.0.0
home: https://github.com/NVIDIA/gpu-operator

dependencies:
  - name: node-feature-discovery
    version: 0.1.0
    condition: nfd.enabled
