apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-device-plugin-mps-control-daemon
  namespace: "FILLED BY THE OPERATOR"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-device-plugin-mps-control-daemon
subjects:
- kind: ServiceAccount
  name: nvidia-device-plugin-mps-control-daemon
  namespace: "FILLED BY THE OPERATOR"
