apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-device-plugin-mps-control-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvidia-device-plugin-mps-control-daemon
subjects:
- kind: ServiceAccount
  name: nvidia-device-plugin-mps-control-daemon
  namespace: "FILLED BY THE OPERATOR"
