apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-gpu-feature-discovery
  namespace: {{ .Namespace }}
rules:
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - resource.k8s.io
  resources:
  - resourceclaims
  verbs:
  - get
  - list
  - watch
