apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-gpu-feature-discovery
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - "nfd.k8s-sigs.io"
  resources:
  - "nodefeatures"
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
