apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-gpu-feature-discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvidia-gpu-feature-discovery
subjects:
- kind: ServiceAccount
  name: nvidia-gpu-feature-discovery
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - "nfd.k8s-sigs.io"
  resources:
  - "nodefeatures"
  verbs:
  - get
  - list
  - watch
  - create
  - update

