apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-feature-discovery-entrypoint
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: gpu-feature-discovery
data:
  entrypoint.sh: |-
    #!/bin/bash

    until [[ -f /run/nvidia/validations/driver-ready ]]
    do
      echo "waiting for the driver validations to be ready..."
      sleep 5
    done

    set -o allexport
    cat /run/nvidia/validations/driver-ready
    . /run/nvidia/validations/driver-ready

    exec gpu-feature-discovery
