apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-feature-discovery
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: gpu-feature-discovery
    app.kubernetes.io/part-of: nvidia-gpu
spec:
  selector:
    matchLabels:
      app: gpu-feature-discovery
      app.kubernetes.io/part-of: nvidia-gpu
  template:
    metadata:
      labels:
        app: gpu-feature-discovery
        app.kubernetes.io/part-of: nvidia-gpu
    spec:
      nodeSelector:
        nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      priorityClassName: system-node-critical
      serviceAccountName: nvidia-gpu-feature-discovery
      initContainers:
        - name: toolkit-validation
          image: "FILLED BY THE OPERATOR"
          command: ['sh', '-c']
          args: ["until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting for nvidia container stack to be setup; sleep 5; done"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: Bidirectional
        - name: config-manager-init
          image: "FILLED BY THE OPERATOR"
          command: ["config-manager"]
          env:
          - name: ONESHOT
            value: "true"
          - name: KUBECONFIG
            value: ""
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: "spec.nodeName"
          - name: NODE_LABEL
            value: "nvidia.com/device-plugin.config"
          - name: CONFIG_FILE_SRCDIR
            value: "/available-configs"
          - name: CONFIG_FILE_DST
            value: "/config/config.yaml"
          - name: DEFAULT_CONFIG
            value: ""
          - name: SEND_SIGNAL
            value: "false"
          - name: SIGNAL
            value: ""
          - name: PROCESS_TO_SIGNAL
            value: ""
      containers:
        - image: "FILLED BY THE OPERATOR"
          name: gpu-feature-discovery
          command: [ "/bin/bash", "-c" ]
          args:
            - /bin/entrypoint.sh
          env:
            - name: GFD_SLEEP_INTERVAL
              value: 60s
            - name: GFD_FAIL_ON_INIT_ERROR
              value: "true"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: gpu-feature-discovery-entrypoint
              readOnly: true
              mountPath: /bin/entrypoint.sh
              subPath: entrypoint.sh
            - name: output-dir
              mountPath: "/etc/kubernetes/node-feature-discovery/features.d"
            - name: dmi-info-dir
              mountPath: "/sys/class/dmi/id"
              readOnly: true
            - name: run-nvidia-validations
              mountPath: /run/nvidia/validations
            - name: driver-install-dir
              mountPath: /driver-root
              mountPropagation: HostToContainer
            - name: host-root
              mountPath: /host
              readOnly: true
              mountPropagation: HostToContainer
          securityContext:
            privileged: true
        - image: "FILLED BY THE OPERATOR"
          name: config-manager
          command: ["config-manager"]
          securityContext:
            privileged: true
          env:
          - name: ONESHOT
            value: "false"
          - name: KUBECONFIG
            value: ""
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: "spec.nodeName"
          - name: NODE_LABEL
            value: "nvidia.com/device-plugin.config"
          - name: CONFIG_FILE_SRCDIR
            value: "/available-configs"
          - name: CONFIG_FILE_DST
            value: "/config/config.yaml"
          - name: DEFAULT_CONFIG
            value: ""
          - name: SEND_SIGNAL
            value: "true"
          - name: SIGNAL
            value: "1" # SIGHUP
          - name: PROCESS_TO_SIGNAL
            value: "gpu-feature-discovery"
      volumes:
        - name: gpu-feature-discovery-entrypoint
          configMap:
            name: gpu-feature-discovery-entrypoint
            defaultMode: 448
        - name: output-dir
          hostPath:
            path: "/etc/kubernetes/node-feature-discovery/features.d"
        - name: dmi-info-dir
          hostPath:
            path: "/sys/class/dmi/id"
        - name: run-nvidia
          hostPath:
            path: "/run/nvidia"
            type: Directory
        - name: run-nvidia-validations
          hostPath:
            path: /run/nvidia/validations
            type: DirectoryOrCreate
        - name: host-root
          hostPath:
            path: /
        - name: driver-install-dir
          hostPath:
            path: /run/nvidia/driver
            type: DirectoryOrCreate
