apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-dra-driver-kubeletplugin
  namespace: gpu-operator
  labels:
    helm.sh/chart: nvidia-dra-driver-26.4.0-dev
    app.kubernetes.io/version: 26.4.0-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nvidia-dra-driver
    app.kubernetes.io/instance: nvidia-dra-driver
