apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-dra-driver
  namespace: "FILLED BY THE OPERATOR"
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
