apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: compute-domain-daemon-role
rules:
- apiGroups:
  - resource.nvidia.com
  resources:
  - computedomains
  - computedomains/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - resource.nvidia.com
  resources:
  - computedomaincliques
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - patch
