apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-dra-driver-clusterrole-binding-controller-gpu-operator
subjects:
- kind: ServiceAccount
  name: nvidia-dra-driver-controller
  namespace: gpu-operator
roleRef:
  kind: ClusterRole
  name: nvidia-dra-driver-clusterrole-controller
  apiGroup: rbac.authorization.k8s.io
