apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-dra-driver-role-kubeletplugin
  namespace: gpu-operator
rules:
- apiGroups:
  - resource.nvidia.com
  resources:
  - computedomaincliques
  verbs:
  - get
