apiVersion: resource.k8s.io/v1alpha3
kind: DeviceClass
metadata:
  name: imex.nvidia.com
spec:
  selectors:
    - cel:
        expression: "device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type == 'imex-channel'"
