#!/usr/bin/env bash

# Copyright NVIDIA CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

# Usage: generate-values-overrides.sh OUTPUT_FILE TOOLKIT_IMAGE DEVICE_PLUGIN_IMAGE MIG_MANAGER_IMAGE
#
# Generates a Helm values override file for GPU Operator component images.
# This file can be used with `helm install -f values-overrides.yaml` to
# override default component image versions.

if [[ $# -ne 4 ]]; then
    echo "Usage: $0 OUTPUT_FILE TOOLKIT_IMAGE DEVICE_PLUGIN_IMAGE MIG_MANAGER_IMAGE" >&2
    echo "" >&2
    echo "Example:" >&2
    echo "  $0 values.yaml \\" >&2
    echo "    ghcr.io/nvidia/container-toolkit:v1.18.0-ubuntu20.04 \\" >&2
    echo "    ghcr.io/nvidia/k8s-device-plugin:v0.17.0-ubi8 \\" >&2
    echo "    ghcr.io/nvidia/k8s-mig-manager:v0.10.0-ubuntu20.04" >&2
    exit 1
fi

OUTPUT_FILE="$1"
TOOLKIT_IMAGE="$2"
DEVICE_PLUGIN_IMAGE="$3"
MIG_MANAGER_IMAGE="$4"

# Generate values override file
cat > "${OUTPUT_FILE}" <<EOF
# Generated by generate-values-overrides.sh
#
# This file overrides default GPU Operator component images with
# specific versions for forward compatibility testing.

toolkit:
  repository: ""
  version: ""
  image: "${TOOLKIT_IMAGE}"

devicePlugin:
  repository: ""
  version: ""
  image: "${DEVICE_PLUGIN_IMAGE}"

migManager:
  repository: ""
  version: ""
  image: "${MIG_MANAGER_IMAGE}"
EOF

echo "Generated values override file: ${OUTPUT_FILE}"
echo ""
echo "=== Component Images ==="
echo "Container Toolkit:  ${TOOLKIT_IMAGE}"
echo "Device Plugin:      ${DEVICE_PLUGIN_IMAGE}"
echo "MIG Manager:        ${MIG_MANAGER_IMAGE}"
echo ""
echo "=== File Contents ==="
cat "${OUTPUT_FILE}"

