resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- envs:
  - .env
  name: gpu-operator-envs-cm
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gpu-operator
  newName: nvcr.io/nvidia/gpu-operator
  newTag: v1.11.0
