apiVersion: v1
kind: Service
metadata:
  name: nvidia-dcgm
  namespace: {{ .Namespace }}
  labels:
    app: nvidia-dcgm
spec:
  type: ClusterIP
  internalTrafficPolicy: Local
  selector:
    app: nvidia-dcgm
  ports:
  - name: "dcgm"
    port: 5555
    targetPort: 5555
    protocol: TCP
