FROM golang:1.13 AS builder
WORKDIR /go/src/github.com/NVIDIA/gpu-operator

COPY . .

RUN go get -u golang.org/x/lint/golint && \
    go get -u github.com/gordonklaus/ineffassign

RUN make build
RUN make verify

FROM ubuntu:18.04
LABEL io.k8s.display-name="NVIDIA GPU Operator"

COPY --from=builder /go/src/github.com/NVIDIA/gpu-operator/gpu-operator  /usr/bin/

RUN mkdir -p /opt/sro
COPY assets /opt/sro/

RUN useradd gpu-operator
USER gpu-operator

ENTRYPOINT ["/usr/bin/gpu-operator"]
