apiVersion: v1
kind: Service
metadata:
  name: gpu-operator
  namespace: "FILLED_BY_THE_OPERATOR"
  labels:
    app: gpu-operator
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: gpu-operator
  ports:
  - name: gpu-operator-metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
