apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gpu-operator
  namespace: "FILLED_BY_THE_OPERATOR"
  labels:
    app: gpu-operator
spec:
  endpoints:
  - port: gpu-operator-metrics
    path: "/metrics"
  jobLabel: operator
  namespaceSelector:
    matchNames:
    - "FILLED_BY_THE_OPERATOR"
  selector:
    matchLabels:
      app: gpu-operator
