apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-container-toolkit
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
    - apps
  resources:
    - daemonsets
  verbs:
    - list
