apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-cuda-validator
  generateName: nvidia-cuda-validator-
  namespace: "FILLED_BY_THE_VALIDATOR"
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: OnFailure
  serviceAccountName: nvidia-operator-validator
  initContainers:
  - name: cuda-validation
    image: "FILLED_BY_THE_VALIDATOR"
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c']
    args: ["vectorAdd"]
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    securityContext:
      privileged: true
  containers:
    - name: nvidia-cuda-validator
      image: "FILLED_BY_THE_VALIDATOR"
      imagePullPolicy: IfNotPresent
      # override command and args as validation is already done by initContainer
      command: ['sh', '-c']
      args: ["echo cuda workload validation is successful"]
      securityContext:
        privileged: true
        readOnlyRootFilesystem: true
