apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-mig-manager
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - delete
