apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-mig-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvidia-mig-manager
subjects:
- kind: ServiceAccount
  name: nvidia-mig-manager
  namespace: "FILLED BY THE OPERATOR"
