apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: gpu-operator-monitoring
  name: nvidia-dcgm-exporter
spec:
  endpoints:
  - port: dcgm 
#  namespaceSelector:
#    matchNames:
#    - gpu-operator
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter

