# Node exporter collecting only GPU metrics from dcgm-exporter.
# Except textfile collector, all other collectors that are enabled by default are disabled.
# Refer: https://github.com/prometheus/node_exporter/tree/release-0.16
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels: 
    app: nvidia-dcgm-exporter
  name: nvidia-dcgm-exporter
  namespace: gpu-operator-monitoring
spec:
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
  template:
    metadata:
      labels:
        app: nvidia-dcgm-exporter
      name: nvidia-dcgm-exporter
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      serviceAccount: nvidia-dcgm-exporter
      serviceAccountName: nvidia-dcgm-exporter
      containers:
      - image: quay.io/zvonkok/dcgm #nvidia/dcgm-exporter:1.4.6
        name: nvidia-dcgm-exporter
        env:
        - name: PYTHONPATH
          value: "/usr/src/dcgm/bindings"
        command: ["python", "/usr/src/dcgm/samples/scripts/dcgm_prometheus.py", "-e", "-p", "9600"]
        securityContext:
          privileged: true
          runAsNonRoot: false
          runAsUser: 0
#        volumeMounts:
#        - name: collector-textfiles
#          mountPath: /run/prometheus

      hostNetwork: true
      hostPID: true

      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
#      - name: collector-textfiles
#        emptyDir:
#          medium: Memory

      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
