FROM ubuntu:18.04
LABEL io.k8s.display-name="NVIDIA GPU Operator"

WORKDIR /go/src/github.com/NVIDIA/gpu-operator

RUN apt-get update && apt-get install -y golang 
COPY . .
RUN GOPATH=/go make build

RUN mkdir -p /opt/sro
COPY assets /opt/sro/

USER root

CMD ["/bin/bash"]
