apiVersion: v1
kind: Service
metadata:
  namespace: "FILLED BY THE OPERATOR"
  name: nvidia-dcgm-exporter
  labels:
    app: nvidia-dcgm-exporter
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: nvidia-dcgm-exporter
  ports:
  - name: gpu-metrics
    port: 9400
    targetPort: 9400
    protocol: TCP
