apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-dcgm-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-dcgm-exporter
data:
  entrypoint.sh: |-
    #!/bin/bash
    chcon -t  container_file_t /var/lib/kubelet/pod-resources
    chcon -t  container_file_t /var/lib/kubelet/pod-resources/*
