apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: specialresources.sro.openshift.io
spec:
  group: sro.openshift.io
  names:
    kind: SpecialResource
    listKind: SpecialResourceList
    plural: specialresources
    singular: specialresource
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
