# permissions for end users to view clusterpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterpolicy-viewer-role
rules:
- apiGroups:
  - nvidia.com
  resources:
  - clusterpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - clusterpolicies/status
  verbs:
  - get
