apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpu-operator-daemonsets-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gpu-operator-daemonsets-role
subjects:
- kind: ServiceAccount
  name: gpu-operator
  namespace: system
