# permissions for end users to edit nvidiadrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidiadriver-editor-role
rules:
- apiGroups:
  - nvidia.com
  resources:
  - nvidiadrivers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - nvidiadrivers/status
  verbs:
  - get
