# permissions for end users to view nvidiadrivers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidiadriver-viewer-role
rules:
- apiGroups:
  - nvidia.com
  resources:
  - nvidiadrivers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - nvidiadrivers/status
  verbs:
  - get
