kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: special-resource-operator
subjects:
- kind: ServiceAccount
  name: special-resource-operator
  namespace: gpu-operator
roleRef:
  kind: ClusterRole
  name: special-resource-operator
  apiGroup: rbac.authorization.k8s.io
