apiVersion: apps/v1
kind: Deployment
metadata:
  name: special-resource-operator
  namespace: gpu-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: special-resource-operator
  template:
    metadata:
      labels:
        name: special-resource-operator
      annotations:
        openshift.io/scc: restricted-readonly
    spec:
      serviceAccount: special-resource-operator
      serviceAccountName: special-resource-operator
      # readOnlyRootFilesystem: true

      containers:
      - name: special-resource-operator
        image: {{ .Values.operator.repository }}/{{ .Values.operator.image }}:{{ .Values.operator.tag }}
        imagePullPolicy: IfNotPresent
        command: ["gpu-operator"]
        envFrom:
        - configMapRef:
            name: operator-config
        env:
        - name: NVIDIA_TOOLKIT_DEFAULT_RUNTIME
          value: "{{ .Values.operator.defaultRuntime }}"
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "special-resource-operator"

        readinessProbe:
          exec:
            command: ["stat", "/tmp/operator-sdk-ready"]

          initialDelaySeconds: 4
          periodSeconds: 10
          failureThreshold: 1
        ports:
        - containerPort: 60000
          name: metrics

      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          value: ""
          effect: "NoSchedule"
