{{- if .Values.gpuCluster.deployCR }}
apiVersion: nvidia.com/v1alpha1
kind: GPUCluster
metadata:
  name: gpu-cluster
  labels:
    {{- include "gpu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gpu-operator"
  {{- if .Values.operator.cleanupCRD }}
  # CR cleanup is handled during pre-delete hook
  # Add below annotation so that helm doesn't attempt to cleanup CR twice
  annotations:
    "helm.sh/resource-policy": keep
  {{- end }}
spec:
  draDriver:
    {{- if .Values.draDriver.repository }}
    repository: {{ .Values.draDriver.repository }}
    {{- end }}
    {{- if .Values.draDriver.image }}
    image: {{ .Values.draDriver.image }}
    {{- end }}
    {{- if .Values.draDriver.version }}
    version: {{ .Values.draDriver.version | quote }}
    {{- end }}
    {{- if .Values.draDriver.imagePullPolicy }}
    imagePullPolicy: {{ .Values.draDriver.imagePullPolicy }}
    {{- end }}
    {{- if .Values.draDriver.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.draDriver.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.draDriver.featureGates }}
    featureGates: {{ toYaml .Values.draDriver.featureGates | nindent 6 }}
    {{- end }}
    {{- if .Values.draDriver.gpus.kubeletPlugin }}
    gpus:
      kubeletPlugin: {{ toYaml .Values.draDriver.gpus.kubeletPlugin | nindent 8 }}
    {{- end }}
    computeDomains:
      enabled: {{ .Values.draDriver.computeDomains.enabled }}
      {{- if .Values.draDriver.computeDomains.controller }}
      controller: {{ toYaml .Values.draDriver.computeDomains.controller | nindent 8 }}
      {{- end }}
      {{- if .Values.draDriver.computeDomains.kubeletPlugin }}
      kubeletPlugin: {{ toYaml .Values.draDriver.computeDomains.kubeletPlugin | nindent 8 }}
      {{- end }}
  dcgm:
    enabled: {{ .Values.dcgm.enabled }}
    {{- if .Values.dcgm.repository }}
    repository: {{ .Values.dcgm.repository }}
    {{- end }}
    {{- if .Values.dcgm.image }}
    image: {{ .Values.dcgm.image }}
    {{- end }}
    {{- if .Values.dcgm.version }}
    version: {{ .Values.dcgm.version | quote }}
    {{- end }}
    {{- if .Values.dcgm.imagePullPolicy }}
    imagePullPolicy: {{ .Values.dcgm.imagePullPolicy }}
    {{- end }}
    {{- if .Values.dcgm.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.dcgm.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgm.args }}
    args: {{ toYaml .Values.dcgm.args | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgm.env }}
    env: {{ toYaml .Values.dcgm.env | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgm.resources }}
    resources: {{ toYaml .Values.dcgm.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgm.hostNetwork }}
    hostNetwork: {{ .Values.dcgm.hostNetwork }}
    {{- end }}
  dcgmExporter:
    enabled: {{ .Values.dcgmExporter.enabled }}
    {{- if .Values.dcgmExporter.repository }}
    repository: {{ .Values.dcgmExporter.repository }}
    {{- end }}
    {{- if .Values.dcgmExporter.image }}
    image: {{ .Values.dcgmExporter.image }}
    {{- end }}
    {{- if .Values.dcgmExporter.version }}
    version: {{ .Values.dcgmExporter.version | quote }}
    {{- end }}
    {{- if .Values.dcgmExporter.imagePullPolicy }}
    imagePullPolicy: {{ .Values.dcgmExporter.imagePullPolicy }}
    {{- end }}
    {{- if .Values.dcgmExporter.imagePullSecrets }}
    imagePullSecrets: {{ toYaml .Values.dcgmExporter.imagePullSecrets | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.annotations }}
    annotations: {{ toYaml .Values.dcgmExporter.annotations | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.args }}
    args: {{ toYaml .Values.dcgmExporter.args | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.env }}
    env: {{ toYaml .Values.dcgmExporter.env | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.resources }}
    resources: {{ toYaml .Values.dcgmExporter.resources | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.hostPID }}
    hostPID: {{ .Values.dcgmExporter.hostPID }}
    {{- end }}
    {{- if .Values.dcgmExporter.hostNetwork }}
    hostNetwork: {{ .Values.dcgmExporter.hostNetwork }}
    {{- end }}
    {{- if .Values.dcgmExporter.hpcJobMapping }}
    hpcJobMapping: {{ toYaml .Values.dcgmExporter.hpcJobMapping | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.enablePodLabels }}
    enablePodLabels: {{ .Values.dcgmExporter.enablePodLabels }}
    {{- end }}
    {{- if .Values.dcgmExporter.enablePodUID }}
    enablePodUID: {{ .Values.dcgmExporter.enablePodUID }}
    {{- end }}
    {{- if .Values.dcgmExporter.podLabelAllowlistRegex }}
    podLabelAllowlistRegex: {{ toYaml .Values.dcgmExporter.podLabelAllowlistRegex | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.service }}
    service: {{ toYaml .Values.dcgmExporter.service | nindent 6 }}
    {{- end }}
    {{- if .Values.dcgmExporter.serviceMonitor }}
    serviceMonitor: {{ toYaml .Values.dcgmExporter.serviceMonitor | nindent 6 }}
    {{- end }}
    {{- if and (.Values.dcgmExporter.config) (.Values.dcgmExporter.config.name) }}
    config:
      name: {{ .Values.dcgmExporter.config.name }}
    {{- end }}
  hostPaths:
    rootFS: {{ .Values.hostPaths.rootFS }}
    driverInstallDir: {{ .Values.hostPaths.driverInstallDir }}
    {{- if .Values.hostPaths.kubeletRootDir }}
    kubeletRootDir: {{ .Values.hostPaths.kubeletRootDir }}
    {{- end }}
  daemonsets: {{ toYaml .Values.daemonsets | nindent 4 }}
{{- end }}
