apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gpu-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: "gpu-operator"
