apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Driver.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Driver.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Driver.Name }}
  namespace: {{ .Runtime.Namespace }}
