FROM golang:1.13 AS builder
WORKDIR /go/src/github.com/NVIDIA/gpu-operator

COPY . .

RUN make build

FROM registry.access.redhat.com/ubi8:latest
LABEL io.k8s.display-name="NVIDIA GPU Operator"

COPY --from=builder /go/src/github.com/NVIDIA/gpu-operator/gpu-operator  /usr/bin/

RUN mkdir -p /opt/gpu-operator
COPY assets/* /opt/gpu-operator/.

RUN useradd gpu-operator
USER gpu-operator

ENTRYPOINT ["/usr/bin/gpu-operator"]
