/**
# Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
**/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	nvidiav1alpha1 "github.com/NVIDIA/gpu-operator/api/nvidia/v1alpha1"
	scheme "github.com/NVIDIA/gpu-operator/api/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GPUClusterConfigsGetter has a method to return a GPUClusterConfigInterface.
// A group's client should implement this interface.
type GPUClusterConfigsGetter interface {
	GPUClusterConfigs() GPUClusterConfigInterface
}

// GPUClusterConfigInterface has methods to work with GPUClusterConfig resources.
type GPUClusterConfigInterface interface {
	Create(ctx context.Context, gPUClusterConfig *nvidiav1alpha1.GPUClusterConfig, opts v1.CreateOptions) (*nvidiav1alpha1.GPUClusterConfig, error)
	Update(ctx context.Context, gPUClusterConfig *nvidiav1alpha1.GPUClusterConfig, opts v1.UpdateOptions) (*nvidiav1alpha1.GPUClusterConfig, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, gPUClusterConfig *nvidiav1alpha1.GPUClusterConfig, opts v1.UpdateOptions) (*nvidiav1alpha1.GPUClusterConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*nvidiav1alpha1.GPUClusterConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*nvidiav1alpha1.GPUClusterConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *nvidiav1alpha1.GPUClusterConfig, err error)
	GPUClusterConfigExpansion
}

// gPUClusterConfigs implements GPUClusterConfigInterface
type gPUClusterConfigs struct {
	*gentype.ClientWithList[*nvidiav1alpha1.GPUClusterConfig, *nvidiav1alpha1.GPUClusterConfigList]
}

// newGPUClusterConfigs returns a GPUClusterConfigs
func newGPUClusterConfigs(c *NvidiaV1alpha1Client) *gPUClusterConfigs {
	return &gPUClusterConfigs{
		gentype.NewClientWithList[*nvidiav1alpha1.GPUClusterConfig, *nvidiav1alpha1.GPUClusterConfigList](
			"gpuclusterconfigs",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *nvidiav1alpha1.GPUClusterConfig { return &nvidiav1alpha1.GPUClusterConfig{} },
			func() *nvidiav1alpha1.GPUClusterConfigList { return &nvidiav1alpha1.GPUClusterConfigList{} },
		),
	}
}
