apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-dra-validator
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: nvidia-dra-validator
    app.kubernetes.io/component: nvidia-dra-validator
