apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-driver-validation
  name: nvidia-driver-validation
  namespace: gpu-operator-resources
spec:
#  serviceAccount: nvidia-readonly
#  serviceAccountName: nvidia-readonly
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  restartPolicy: Never
  containers:
    - name: cuda-vector-add
      image: "quay.io/zvonkok/cuda-vector-add:v0.1"
      #image: "quay.io/zvonkok/cuda:10.1-samples-ubi8"
      #command: ["/usr/local/cuda/samples/bin/x86_64/linux/release/vectorAdd"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA  
          value: "cuda>=5.0"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
  nodeSelector:
    feature.node.kubernetes.io/pci-10de.present: "true"
