apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nvidia-vgpu-manager
  namespace: "FILLED BY THE OPERATOR"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-vgpu-manager
subjects:
- kind: ServiceAccount
  name: nvidia-vgpu-manager
  namespace: "FILLED BY THE OPERATOR"
