apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-kata-sandbox-device-plugin
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - create
  - get
  - list
  - watch
  - update
