/**
# Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
**/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/NVIDIA/gpu-operator/api/nvidia/v1alpha1"
	nvidiav1alpha1 "github.com/NVIDIA/gpu-operator/api/versioned/typed/nvidia/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGPUClusters implements GPUClusterInterface
type fakeGPUClusters struct {
	*gentype.FakeClientWithList[*v1alpha1.GPUCluster, *v1alpha1.GPUClusterList]
	Fake *FakeNvidiaV1alpha1
}

func newFakeGPUClusters(fake *FakeNvidiaV1alpha1) nvidiav1alpha1.GPUClusterInterface {
	return &fakeGPUClusters{
		gentype.NewFakeClientWithList[*v1alpha1.GPUCluster, *v1alpha1.GPUClusterList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("gpuclusters"),
			v1alpha1.SchemeGroupVersion.WithKind("GPUCluster"),
			func() *v1alpha1.GPUCluster { return &v1alpha1.GPUCluster{} },
			func() *v1alpha1.GPUClusterList { return &v1alpha1.GPUClusterList{} },
			func(dst, src *v1alpha1.GPUClusterList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GPUClusterList) []*v1alpha1.GPUCluster { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.GPUClusterList, items []*v1alpha1.GPUCluster) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
