/**
# Copyright (c) NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
**/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/NVIDIA/gpu-operator/api/nvidia/v1alpha1"
	nvidiav1alpha1 "github.com/NVIDIA/gpu-operator/api/versioned/typed/nvidia/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeGPUClusterConfigs implements GPUClusterConfigInterface
type fakeGPUClusterConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.GPUClusterConfig, *v1alpha1.GPUClusterConfigList]
	Fake *FakeNvidiaV1alpha1
}

func newFakeGPUClusterConfigs(fake *FakeNvidiaV1alpha1) nvidiav1alpha1.GPUClusterConfigInterface {
	return &fakeGPUClusterConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.GPUClusterConfig, *v1alpha1.GPUClusterConfigList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("gpuclusterconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("GPUClusterConfig"),
			func() *v1alpha1.GPUClusterConfig { return &v1alpha1.GPUClusterConfig{} },
			func() *v1alpha1.GPUClusterConfigList { return &v1alpha1.GPUClusterConfigList{} },
			func(dst, src *v1alpha1.GPUClusterConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.GPUClusterConfigList) []*v1alpha1.GPUClusterConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.GPUClusterConfigList, items []*v1alpha1.GPUClusterConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
