apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-vfio-manager
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-vfio-manager
spec:
  selector:
    matchLabels:
      name: nvidia-vfio-manager
  template:
    metadata:
      labels:
        name: nvidia-vfio-manager
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.deploy.vfio-manager: "true"
      priorityClassName: system-node-critical
      serviceAccountName: nvidia-vfio-manager
      initContainers:
        - name: k8s-driver-manager
          image: "FILLED BY THE OPERATOR"
          imagePullPolicy: IfNotPresent
          command: ["driver-manager"]
          args: ["uninstall_driver"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          # always use runc for driver containers
          - name: NVIDIA_VISIBLE_DEVICES
            value: void
          - name: ENABLE_GPU_POD_EVICTION
            value: "false"
          - name: ENABLE_AUTO_DRAIN
            value: "false"
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          securityContext:
            privileged: true
          volumeMounts:
            - name: run-nvidia
              mountPath: /run/nvidia
              mountPropagation: Bidirectional
            - name: host-root
              mountPath: /host
              readOnly: true
              mountPropagation: HostToContainer
            - name: host-sys
              mountPath: /sys
      containers:
        - name: nvidia-vfio-manager
          image: "FILLED BY THE OPERATOR"
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - vfio-manage bind --all && while true; do sleep 86400; done
          env:
            - name: HOST_ROOT
              value: "/host"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: host-sys
            mountPath: /sys
          - name: host-lib-modules
            mountPath: /lib/modules
            readOnly: true
          - name: host-root
            mountPath: /host
          - name: run-nvidia-validations
            mountPath: /run/nvidia/validations
            mountPropagation: Bidirectional
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0"
          lifecycle:
            preStop:
              exec:
                command: ["vfio-manage unbind --all"]
      terminationGracePeriodSeconds: 30
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: host-lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: DirectoryOrCreate
        - name: run-nvidia-validations
          hostPath:
            path: /run/nvidia/validations
            type: DirectoryOrCreate
        - name: host-root
          hostPath:
            path: "/"
