apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-driver
  namespace: gpu-operator-resources
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
