apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-node-status-exporter
  namespace: gpu-operator-resources
  labels:
    app: nvidia-node-status-exporter
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - gpu-operator-privileged
