apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-node-status-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-node-status-exporter
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
