apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-node-status-exporter
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-node-status-exporter
spec:
  endpoints:
  - port: node-status
    path: "/metrics"
  jobLabel: node-status
  namespaceSelector:
    matchNames:
    - "FILLED BY THE OPERATOR"
  selector:
    matchLabels:
     app: nvidia-node-status-exporter
