apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-dra-driver-kubeletplugin
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: nvidia-dra-driver
    app.kubernetes.io/component: nvidia-dra-driver-kubelet-plugin
