{{- if .DRADriver.Spec.IsGPUsEnabled }}
apiVersion: {{ .DeviceClassAPIVersion }}
kind: DeviceClass
metadata:
  name: gpu.nvidia.com
spec:
  selectors:
    - cel:
        expression: "device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type == 'gpu'"
{{- end }}
