{{- if .DRADriver.Spec.IsComputeDomainsEnabled }}
apiVersion: {{ .DeviceClassAPIVersion }}
kind: DeviceClass
metadata:
  name: compute-domain-daemon.nvidia.com
spec:
  selectors:
    - cel:
        expression: "device.driver == 'compute-domain.nvidia.com' && device.attributes['compute-domain.nvidia.com'].type == 'daemon'"
---
apiVersion: {{ .DeviceClassAPIVersion }}
kind: DeviceClass
metadata:
  name: compute-domain-default-channel.nvidia.com
spec:
  selectors:
    - cel:
        expression: "device.driver == 'compute-domain.nvidia.com' && device.attributes['compute-domain.nvidia.com'].type == 'channel' && device.attributes['compute-domain.nvidia.com'].id == 0"
{{- end }}
