apiVersion: {{ .DeviceClassAPIVersion }}
kind: DeviceClass
metadata:
  name: vfio.gpu.nvidia.com
spec:
  selectors:
    - cel:
        expression: "device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].type == 'vfio'"
