apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nvidia-operator-validator
  namespace: "FILLED BY THE OPERATOR"
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - gpu-operator-privileged
- apiGroups:
  - nvidia.com
  resources:
  - clusterpolicies/finalizers
  verbs:
  - '*'
