apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidia-operator-validator
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nvidia.com
  resources:
  - clusterpolicies/finalizers
  - nvidiadrivers/finalizers
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
