apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-operator-validator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nvidia-operator-validator
subjects:
- kind: ServiceAccount
  name: nvidia-operator-validator
  namespace: "FILLED BY THE OPERATOR"
