apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-cc-manager
  namespace: "FILLED BY THE OPERATOR"
  labels:
    app: nvidia-cc-manager
spec:
  selector:
    matchLabels:
      name: nvidia-cc-manager
  template:
    metadata:
      labels:
        name: nvidia-cc-manager
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.deploy.cc-manager: "true"
        nvidia.com/cc.capable: "true"
      priorityClassName: system-node-critical
      serviceAccountName: nvidia-cc-manager
      containers:
        - name: nvidia-cc-manager
          image: "FILLED BY THE OPERATOR"
          imagePullPolicy: IfNotPresent
          command: ["k8s-cc-manager"]
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CC_CAPABLE_DEVICE_IDS
            value: "0x2322,0x2331"
          # always use runc for driver containers
          - name: NVIDIA_VISIBLE_DEVICES
            value: void
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
          - name: host-sys
            mountPath: /sys
          - name: run-nvidia
            mountPath: /run/nvidia
          securityContext:
            privileged: true
            seLinuxOptions:
              level: "s0"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -f /run/nvidia/validations/.cc-manager-ctr-ready"]
      terminationGracePeriodSeconds: 30
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
            type: Directory
        - name: run-nvidia
          hostPath:
            path: /run/nvidia
            type: DirectoryOrCreate
