name: Renovate

on:
  workflow_dispatch:
  schedule:
     - cron: "0 9 * * *" # every day at 9:00 AM UTC

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Run Renovate
        uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c # v46.2.5
        with:
          configurationFile: .github/renovate.json
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_REPOSITORIES: '["NVIDIA/gpu-operator"]'
          RENOVATE_ONBOARDING: false
