apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nvidia-device-plugin-validation
  name: nvidia-device-plugin-validation
  namespace: gpu-operator-resources
spec:
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
  serviceAccount: nvidia-device-plugin
  serviceAccountName: nvidia-device-plugin
  readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  containers:
    - name: cuda-vector-add
      image: "quay.io/zvonkok/cuda:10.1-samples-ubi8"
      command: ["/usr/local/cuda/samples/bin/x86_64/linux/release/vectorAdd"]
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA  
          value: "cuda>=5.0"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU